# PostgreSQL Database Configuration
# To make this portable, just change these values depending on where the database is hosted.
db.url=jdbc:postgresql://localhost:5432/game_db
db.username=postgres
db.password=password
